class Symbol:
    def __init__(self, name: str, round: int):
        self.name = name
        self.round = round
        if self.name == "A":
            self.H_WALL = "━"
            self.V_WALL = "┃"
            self.FILL = " "
            self.DOT = "╋"
            self.ENTRY = "#"
            self.EXIT = "$"
            self.PATH = "%"
            self.ULCOIN = "┏"
            self.URCOIN = "┓"
            self.DLCOIN = "┗"
            self.DRCOIN = "┛"
            self.LEFT = "┣"
            self.RIGHT = "┫"
            self.UP = "┳"
            self.DOWN = "┻"
        elif self.name == "B":
            self.H_WALL = "─"
            self.V_WALL = "│"
            self.FILL = " "
            self.DOT = "┼"
            self.ENTRY = "#"
            self.EXIT = "$"
            self.PATH = "%"
            self.ULCOIN = "╭"
            self.URCOIN = "╮"
            self.DLCOIN = "╰"
            self.DRCOIN = "╯"
            self.LEFT = "├"
            self.RIGHT = "┤"
            self.UP = "┬"
            self.DOWN = "┴"
        elif self.name == "C":
            self.H_WALL = "═"
            self.V_WALL = "║"
            self.FILL = " "
            self.DOT = "╬"
            self.ENTRY = "#"
            self.EXIT = "$"
            self.PATH = "%"
            self.ULCOIN = "╔"
            self.URCOIN = "╗"
            self.DLCOIN = "╚"
            self.DRCOIN = "╝"
            self.LEFT = "╠"
            self.RIGHT = "╣"
            self.UP = "╦"
            self.DOWN = "╩"
